# Generated by Django 6.0.2 on 2026-02-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('JPY', '¥'), ('INR', '₹'), ('AUD', 'A$'), ('CAD', 'C$'), ('CHF', 'CHF'), ('CNY', '¥'), ('KRW', '₩'), ('SGD', 'S$'), ('NZD', 'NZ$')], max_length=50, null=True),
        ),
    ]
