# Generated by Django 6.0.2 on 2026-02-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('JPY', '¥'), ('INR', '₹'), ('AUD', 'A$'), ('CAD', 'C$'), ('CHF', 'CHF'), ('CNY', '¥'), ('KRW', '₩'), ('SGD', 'S$'), ('NZD', 'NZ$')], default='₹', max_length=50, null=True),
        ),
    ]
