# Generated by Django 6.0.2 on 2026-02-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_sitesettings_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='currency',
            field=models.CharField(choices=[('INR', '₹'), ('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('JPY', '¥'), ('AUD', 'A$'), ('CAD', 'C$'), ('CHF', 'CHF'), ('CNY', '¥'), ('KRW', '₩'), ('SGD', 'S$'), ('NZD', 'NZ$')], default={'AUD': 'A$', 'CAD': 'C$', 'CHF': 'CHF', 'CNY': '¥', 'EUR': '€', 'GBP': '£', 'INR': '₹', 'JPY': '¥', 'KRW': '₩', 'NZD': 'NZ$', 'SGD': 'S$', 'USD': '$'}, max_length=50, null=True),
        ),
    ]
