# Generated by Django 6.0.2 on 2026-02-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_sitesettings_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='currency',
            field=models.CharField(choices=[('₹', 'INR'), ('$', 'USD'), ('€', 'EUR'), ('£', 'GBP'), ('¥', 'JPY'), ('A$', 'AUD'), ('C$', 'CAD'), ('CHF', 'CHF'), ('₩', 'KRW'), ('S$', 'SGD'), ('NZ$', 'NZD')], default='INR', max_length=50, null=True),
        ),
    ]
