# Generated by Django 6.0.2 on 2026-03-04 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_cart_created_at_alter_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 4, 22, 38, 37, 595849), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 4, 22, 38, 37, 596512), null=True),
        ),
    ]
