# Generated by Django 6.0.2 on 2026-03-09 06:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_cart_created_at_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 9, 12, 22, 58, 876220), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 9, 12, 22, 58, 876897), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ordered', 'ordered'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('canceled', 'canceled')], default='ordered', max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_cat',
            field=models.CharField(choices=[('fruit', 'fruit'), ('vegitable', 'vegitable'), ('biscuit', 'biscuit'), ('snack', 'snack'), ('cup', 'cup'), ('meats', 'meats'), ('frozen', 'frozen'), ('grocery', 'grocery'), ('drink', 'drink')], default='fruit', max_length=100),
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
            ],
        ),
    ]
