# Generated by Django 6.0.2 on 2026-03-09 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_cart_created_at_alter_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 9, 13, 40, 0, 276963), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 9, 13, 40, 0, 277721), null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.JSONField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.JSONField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.JSONField(default=0, null=True),
        ),
    ]
