# Generated by Django 6.0.2 on 2026-03-09 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_cart_created_at_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 9, 16, 20, 32, 750647), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 9, 16, 20, 32, 751126), null=True),
        ),
    ]
